# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import eventify_pb2 as eventify__pb2


class EventifyStub(object):
    """Sort of like event notify, but shorter
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/eventify.Eventify/Subscribe',
                request_serializer=eventify__pb2.SubRequest.SerializeToString,
                response_deserializer=eventify__pb2.Event.FromString,
                )


class EventifyServicer(object):
    """Sort of like event notify, but shorter
    """

    def Subscribe(self, request, context):
        """Subscribe for a particular event type
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=eventify__pb2.SubRequest.FromString,
                    response_serializer=eventify__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eventify.Eventify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Eventify(object):
    """Sort of like event notify, but shorter
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/eventify.Eventify/Subscribe',
            eventify__pb2.SubRequest.SerializeToString,
            eventify__pb2.Event.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
