# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eventify.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eventify.proto',
  package='eventify',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x65ventify.proto\x12\x08\x65ventify\"/\n\nSubRequest\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.eventify.EventType\"\x91\x01\n\x05\x45vent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x04type\x18\x02 \x01(\x0e\x32\x13.eventify.EventType\x12+\n\tinstances\x18\x03 \x03(\x0b\x32\x18.eventify.Event.Instance\x1a*\n\x08Instance\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t*6\n\tEventType\x12\x0b\n\x07\x43ONCERT\x10\x00\x12\x0e\n\nCONFERENCE\x10\x01\x12\x0c\n\x08\x46\x45STIVAL\x10\x02\x32@\n\x08\x45ventify\x12\x34\n\tSubscribe\x12\x14.eventify.SubRequest\x1a\x0f.eventify.Event0\x01\x62\x06proto3'
)

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='eventify.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONCERT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFERENCE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FESTIVAL', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=225,
  serialized_end=279,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
CONCERT = 0
CONFERENCE = 1
FESTIVAL = 2



_SUBREQUEST = _descriptor.Descriptor(
  name='SubRequest',
  full_name='eventify.SubRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='eventify.SubRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=75,
)


_EVENT_INSTANCE = _descriptor.Descriptor(
  name='Instance',
  full_name='eventify.Event.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='eventify.Event.Instance.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='eventify.Event.Instance.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=223,
)

_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='eventify.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='eventify.Event.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='eventify.Event.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instances', full_name='eventify.Event.instances', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_INSTANCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=223,
)

_SUBREQUEST.fields_by_name['type'].enum_type = _EVENTTYPE
_EVENT_INSTANCE.containing_type = _EVENT
_EVENT.fields_by_name['type'].enum_type = _EVENTTYPE
_EVENT.fields_by_name['instances'].message_type = _EVENT_INSTANCE
DESCRIPTOR.message_types_by_name['SubRequest'] = _SUBREQUEST
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubRequest = _reflection.GeneratedProtocolMessageType('SubRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBREQUEST,
  '__module__' : 'eventify_pb2'
  # @@protoc_insertion_point(class_scope:eventify.SubRequest)
  })
_sym_db.RegisterMessage(SubRequest)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {

  'Instance' : _reflection.GeneratedProtocolMessageType('Instance', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_INSTANCE,
    '__module__' : 'eventify_pb2'
    # @@protoc_insertion_point(class_scope:eventify.Event.Instance)
    })
  ,
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'eventify_pb2'
  # @@protoc_insertion_point(class_scope:eventify.Event)
  })
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.Instance)



_EVENTIFY = _descriptor.ServiceDescriptor(
  name='Eventify',
  full_name='eventify.Eventify',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=281,
  serialized_end=345,
  methods=[
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='eventify.Eventify.Subscribe',
    index=0,
    containing_service=None,
    input_type=_SUBREQUEST,
    output_type=_EVENT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTIFY)

DESCRIPTOR.services_by_name['Eventify'] = _EVENTIFY

# @@protoc_insertion_point(module_scope)
